# Generated by Django 2.2.12 on 2020-07-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAcademia', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Academias',
            },
        ),
        migrations.CreateModel(
            name='EnderecoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Endereço/Aluno',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=100)),
                ('academiaProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liganacional.Academia')),
            ],
            options={
                'verbose_name_plural': 'Academias',
            },
        ),
        migrations.CreateModel(
            name='Federacao',
            fields=[
                ('nomeFederacao', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cidadeFederacao', models.CharField(max_length=100)),
                ('professores', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liganacional.Professor')),
            ],
            options={
                'verbose_name_plural': 'Federações',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=100)),
                ('enderecos', models.ManyToManyField(to='liganacional.EnderecoAluno')),
            ],
            options={
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
