# Generated by Django 2.2.12 on 2020-07-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liganacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Amador 50/54kg', 'Amador 50/54kg'), ('Amador 55/59kg', 'Amador 55/59kg'), ('Amador 60/64kg', 'Amador 60/64kg'), ('Amador 65/69kg', 'Amador 65/69kg'), ('Amador 70/74kg', 'Amador 70/74kg'), ('Amador 75/79kg', 'Amador 75/79kg'), ('APERSONALIZADA', 'Amador Personalizada')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nomeAluno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='EnderecoAluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='categorias',
            field=models.ManyToManyField(to='liganacional.CategoriaAluno'),
        ),
    ]
