# Generated by Django 2.2.12 on 2020-07-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liganacional', '0002_auto_20200702_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoLuta', models.CharField(choices=[('Acre', 'Acre'), ('Alagoas', 'Alagoas'), ('Amapá', 'Amapá'), ('Amazonas', 'Amazonas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Distrito Federal', 'Distrito Federal'), ('Espírito Santo', 'Espírito Santo'), ('Goiás', 'Goiás'), ('Maranhão', 'Maranhão'), ('Mato Grosso', 'Mato Grosso'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Minas Gerais', 'Minas Gerais'), ('Pará', 'Pará'), ('Paraíba', 'Paraíba'), ('Paraná', 'Paraná'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio de Janeiro', 'Rio de Janeiro'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Rondônia', 'Rondônia'), ('Santa Catarina', 'Santa Catarina'), ('São Paulo', 'São Paulo'), ('Sergipe', 'Sergipe'), ('Tocantins', 'Tocantins')], max_length=1)),
                ('federacaoCamp', models.ManyToManyField(to='liganacional.Federacao')),
            ],
            options={
                'verbose_name_plural': 'Datas de Campeonatos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='academiaTreino',
            field=models.ManyToManyField(to='liganacional.Academia'),
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='categorias',
        ),
        migrations.AddField(
            model_name='aluno',
            name='categorias',
            field=models.CharField(choices=[('Amador 50/54kg', 'Amador 50/54kg'), ('Amador 55/59kg', 'Amador 55/59kg'), ('Amador 60/64kg', 'Amador 60/64kg'), ('Amador 65/69kg', 'Amador 65/69kg'), ('Amador 70/74kg', 'Amador 70/74kg'), ('Amador 75/79kg', 'Amador 75/79kg'), ('Amador PERSONALIZADA', 'Amador Personalizada'), ('Semi Pro 50/54kg', 'Semi Pro 50/54kg'), ('Semi Pro 55/59kg', 'Semi Pro 55/59kg'), ('Semi Pro 60/64kg', 'Semi Pro 60/64kg'), ('Semi Pro 65/69kg', 'Semi Pro 65/69kg'), ('Semi Pro 70/74kg', 'Semi Pro 70/74kg'), ('Semi Pro 75/79kg', 'Semi Pro 75/79kg'), ('Semi Pro PERSONALIZADA', 'Semi Pro Personalizada'), ('Profissional 50/54kg', 'Profissional 50/54kg'), ('Profissional 55/59kg', 'Profissional 55/59kg'), ('Profissional 60/64kg', 'Profissional 60/64kg'), ('Profissional 65/69kg', 'Profissional 65/69kg'), ('Profissional 70/74kg', 'Profissional 70/74kg'), ('Profissional 75/79kg', 'Profissional 75/79kg'), ('Profissional PERSONALIZADA', 'Profissional Personalizada')], default='', max_length=1),
        ),
        migrations.DeleteModel(
            name='CategoriaAluno',
        ),
    ]
