# Generated by Django 2.2.12 on 2020-07-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liganacional', '0004_auto_20200702_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutas',
            name='dataCamp',
            field=models.CharField(default='', max_length=8),
        ),
    ]
